---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: https://www.shore.co.il/git/shell-pre-commit/
    sha: v0.5.4
    hooks:
    -   id: shell-lint
        files: shell-lint
    -   id: shellcheck
        files: shell-lint
