---
- id: shell-lint
  name: Lint shell scripts
  description: Run /bin/sh -en against shell scripts.
  language: script
  entry: ./shell-lint
  types: [shell]
  minimum_pre_commit_version: 0.15.0 #  Because of types.
- id: shellcheck
  name: shellcheck
  description: A shell script static analysis tool
  language: system
  entry: shellcheck
  args: ['--external-sources']
  types: [shell]
  minimum_pre_commit_version: 0.15.0 #  Because of types.
