---
language: python
python: "3.5"
dist: trusty
sudo: false

cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - pip install pre_commit

script:
  - pre-commit run --all-files

notifications:
  email: false
